import { useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { API_BASE_URL } from "../services/api";

type Mode = "login" | "register";
interface CustomerAuthResponse { access_token:string; token_type:string; customer_id?:number; name?:string; email:string; role:"admin"|"customer"; }
function CustomerAuth(){
 const navigate=useNavigate();const[mode,setMode]=useState<Mode>("login");const[name,setName]=useState("");const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[password,setPassword]=useState("");const[confirmPassword,setConfirmPassword]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");if(mode==="register"&&password!==confirmPassword){setError("Passwords do not match");return}setLoading(true);try{const normalizedEmail=email.trim().toLowerCase();const endpoint=mode==="register"?"register":"login";const response=await fetch(`${API_BASE_URL}/customer-auth/${endpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(mode==="register"?{name:name.trim(),email:normalizedEmail,phone:phone||null,password}:{email:normalizedEmail,password})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail||"Authentication failed");const data:CustomerAuthResponse=body;if(mode==="login"&&data.role==="admin"){localStorage.removeItem("customer_access_token");localStorage.removeItem("customer");localStorage.setItem("access_token",data.access_token);localStorage.setItem("token_type",data.token_type);navigate("/dashboard",{replace:true});return}localStorage.removeItem("access_token");localStorage.removeItem("token_type");localStorage.setItem("customer_access_token",data.access_token);localStorage.setItem("customer",JSON.stringify({id:data.customer_id,name:data.name,email:data.email}));window.dispatchEvent(new Event("coffeehub:customer-auth"));navigate("/",{replace:true});}catch(err){setError(err instanceof Error?err.message:"Authentication failed")}finally{setLoading(false)}};
 return <main className="coffee-auth-page"><div className="coffee-auth-glow"/><div className="coffee-auth-shell"><section className="coffee-auth-brand"><button onClick={()=>navigate("/")} className="coffee-auth-logo"><span>☕</span><b>CoffeeHub<small>Specialty Coffee</small></b></button><div><p>COFFEE. CRAFT. COMMUNITY.</p><h1>Your next favourite<br/><i>cup starts here.</i></h1><span>Discover better coffee, remember your favourites, and keep every order close.</span></div><small>Made for everyday coffee rituals.</small></section><section className="coffee-auth-form"><button onClick={()=>navigate("/")} className="coffee-auth-back">← Back to CoffeeHub</button><p className="section-kicker">COFFEEHUB MEMBERSHIP</p><h2>{mode==="login"?"Welcome back.":"Join the coffee club."}</h2><p className="coffee-auth-sub">{mode==="login"?"Sign in and continue your coffee journey.":"Create an account for faster checkout and order history."}</p><div className="coffee-auth-tabs"><button type="button" onClick={()=>{setMode("login");setError("")}} className={mode==="login"?"active":""}>Sign in</button><button type="button" onClick={()=>{setMode("register");setError("")}} className={mode==="register"?"active":""}>Create account</button></div><form onSubmit={submit} className="coffee-auth-fields">{mode==="register"&&<><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" minLength={2} required/></label><label>Phone <em>(optional)</em><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="98765 43210"/></label></>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters" minLength={8} required/></label>{mode==="register"&&<label>Confirm password<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Repeat your password" minLength={8} required/></label>}{error&&<div className="coffee-auth-error">{error}</div>}<button disabled={loading} className="coffee-auth-submit" type="submit">{loading?"Please wait...":mode==="login"?"Continue to CoffeeHub →":"Create my account →"}</button></form><small className="coffee-auth-note">One secure login for customers and administrators.</small></section></div></main>;
}
export default CustomerAuth;
