import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
interface Order { id: number; customer_name: string; total: number; status: string; created_at: string; items: { coffee_name: string; quantity: number }[]; }
interface Customer { id: number; name: string; }
interface Coffee { id: number; name: string; is_available: boolean; }

function Dashboard() {
  const navigate = useNavigate(); const [orders, setOrders] = useState<Order[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [coffees, setCoffees] = useState<Coffee[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const handleLogout = () => { localStorage.removeItem("access_token"); localStorage.removeItem("token_type"); navigate("/login", { replace: true }); };
  const loadDashboard = async () => { setLoading(true); setError(""); try { const token = localStorage.getItem("access_token"); const headers = { Authorization: `Bearer ${token}` }; const [ordersResponse, customersResponse, coffeesResponse] = await Promise.all([fetch("http://127.0.0.1:8000/admin/orders/", { headers }), fetch("http://127.0.0.1:8000/customers/", { headers }), fetch("http://127.0.0.1:8000/coffees/", { headers })]); if ([ordersResponse, customersResponse, coffeesResponse].some(r => r.status === 401)) { localStorage.removeItem("access_token"); navigate("/login", { replace: true }); return; } if (!ordersResponse.ok || !customersResponse.ok || !coffeesResponse.ok) throw new Error("Unable to load dashboard data"); setOrders(await ordersResponse.json()); setCustomers(await customersResponse.json()); setCoffees(await coffeesResponse.json()); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load dashboard data"); } finally { setLoading(false); } };
  useEffect(() => { loadDashboard(); }, []);
  const revenue = useMemo(() => orders.filter(o => o.status !== "cancelled").reduce((sum, o) => sum + o.total, 0), [orders]); const activeOrders = orders.filter(o => ["pending", "confirmed", "preparing", "ready", "out_for_delivery"].includes(o.status)).length; const recentOrders = orders.slice(0, 5);
  const statusClass = (status: string) => status === "delivered" ? "bg-emerald-50 text-emerald-700" : status === "cancelled" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700";
  const navItems = [{ label: "Overview", icon: "⌂", action: () => navigate("/dashboard") }, { label: "Customers", icon: "♙", action: () => navigate("/customers") }, { label: "Coffee Menu", icon: "☕", action: () => navigate("/coffees") }, { label: "Orders", icon: "▣", action: () => navigate("/admin/orders") }];
  return <div className="min-h-screen bg-[#f7efe5] text-[#241610]"><div className="flex min-h-screen">
    <aside className="hidden lg:flex w-72 shrink-0 flex-col bg-[#1b120e] text-white px-6 py-7 sticky top-0 h-screen border-r border-white/5"><button onClick={() => navigate("/")} className="text-left mb-12"><div className="flex items-center gap-3"><span className="w-12 h-12 rounded-2xl bg-[#f4e5d7] text-[#5a321f] flex items-center justify-center text-2xl shadow-lg">☕</span><div><div className="text-xl font-black tracking-tight">CoffeeHub</div><div className="text-[10px] uppercase tracking-[.28em] text-[#d8b99d]">Admin Studio</div></div></div></button><div className="text-[10px] uppercase tracking-[.28em] text-[#a98b78] mb-3 px-3">Workspace</div><nav className="space-y-1.5">{navItems.map((item, index) => <button key={item.label} onClick={item.action} className={`w-full flex items-center gap-3 px-4 py-3.5 rounded-xl text-left transition ${index === 0 ? "bg-[#f4e5d7] text-[#321c12] shadow-lg" : "text-[#ead9cc] hover:bg-white/10"}`}><span className="w-7 text-center text-lg">{item.icon}</span><span className="font-semibold">{item.label}</span></button>)}</nav><div className="mt-auto space-y-2"><button onClick={() => navigate("/")} className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-left text-[#ead9cc] hover:bg-white/10">↗ <span>View website</span></button><button onClick={handleLogout} className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-left text-[#e9b7a9] hover:bg-red-500/10">↪ <span>Sign out</span></button></div></aside>
    <main className="flex-1 min-w-0"><header className="bg-[#fffaf4]/95 backdrop-blur border-b border-[#e7d8c9] px-5 sm:px-8 lg:px-10 py-5 flex items-center justify-between sticky top-0 z-20"><div><p className="text-[10px] uppercase tracking-[.3em] text-[#a16d45] font-bold">CoffeeHub / Operations</p><h1 className="text-xl sm:text-2xl font-black mt-1">Command Center</h1></div><div className="flex items-center gap-3"><button onClick={() => navigate("/")} className="hidden sm:inline-flex rounded-full border border-[#dfcdbb] bg-white px-4 py-2 text-sm font-semibold hover:bg-[#f7eee5]">↗ View site</button><div className="w-10 h-10 rounded-full bg-[#e7c9aa] text-[#4a2819] flex items-center justify-center font-black">A</div></div></header>
      <div className="px-5 sm:px-8 lg:px-10 py-8 max-w-[1500px] mx-auto"><div className="flex flex-col xl:flex-row xl:items-end justify-between gap-5 mb-8"><div><p className="text-xs uppercase tracking-[.28em] text-[#a16d45] font-bold">Good morning</p><h2 className="text-3xl sm:text-4xl font-black tracking-[-.035em] mt-2">Welcome back, Administrator.</h2><p className="text-[#7d6a5d] mt-2">Everything you need to run CoffeeHub today.</p></div><div className="flex gap-2"><button onClick={loadDashboard} className="rounded-xl border border-[#dfcdbb] bg-white px-4 py-3 font-semibold hover:bg-[#fffaf4]">Refresh</button><button onClick={() => navigate("/admin/orders")} className="rounded-xl bg-[#241610] hover:bg-[#5a321f] text-white px-5 py-3 font-bold shadow-lg">Manage orders →</button></div></div>
        {error && <div className="bg-red-50 border border-red-100 text-red-700 rounded-xl px-4 py-3 mb-6">{error}</div>}
        {loading ? <div className="bg-[#fffaf4] rounded-3xl border border-[#e8d9ca] p-14 text-center text-[#806b5e]">Preparing your workspace...</div> : <><section className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-8">{[["Orders", orders.length.toString(), "All incoming orders", "▣"], ["Revenue", `₹${revenue.toFixed(0)}`, "Excluding cancelled", "₹"], ["Customers", customers.length.toString(), "Registered customers", "♙"], ["Coffee Menu", coffees.filter(c => c.is_available).length.toString(), "Available items", "☕"]].map(([title, value, meta, icon]) => <div key={title} className="bg-[#fffaf4] rounded-2xl border border-[#e8d9ca] p-5 shadow-sm hover:-translate-y-1 hover:shadow-lg transition-all"><div className="flex items-start justify-between"><div><p className="text-sm text-[#806b5e]">{title}</p><p className="text-2xl font-black mt-2">{value}</p></div><span className="w-11 h-11 rounded-xl bg-[#f1dfce] text-[#633821] flex items-center justify-center text-xl">{icon}</span></div><p className="text-xs text-[#9b877a] mt-4">{meta}</p></div>)}</section>
          <section className="grid grid-cols-1 xl:grid-cols-3 gap-6"><div className="xl:col-span-2 bg-[#fffaf4] rounded-3xl border border-[#e8d9ca] shadow-sm overflow-hidden"><div className="px-6 py-5 border-b border-[#eee2d6] flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-[#a16d45] font-bold">Live activity</p><h3 className="text-xl font-black mt-1">Recent Orders</h3></div><span className="text-xs font-bold text-[#806b5e]">{activeOrders} active</span></div>{recentOrders.length ? <div className="overflow-x-auto"><table className="w-full text-left min-w-[650px]"><thead className="bg-[#fbf5ee] text-xs uppercase tracking-wider text-[#907969]"><tr><th className="px-6 py-4">Order</th><th className="px-6 py-4">Customer</th><th className="px-6 py-4">Items</th><th className="px-6 py-4">Total</th><th className="px-6 py-4">Status</th></tr></thead><tbody className="divide-y divide-[#eee5de] text-sm">{recentOrders.map(order => <tr key={order.id} className="hover:bg-[#fff9f3]"><td className="px-6 py-4 font-bold">#{order.id}</td><td className="px-6 py-4">{order.customer_name}</td><td className="px-6 py-4 text-[#78665b]">{order.items.map(i => `${i.coffee_name} × ${i.quantity}`).join(", ")}</td><td className="px-6 py-4 font-bold">₹{order.total}</td><td className="px-6 py-4"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold capitalize ${statusClass(order.status)}`}>{order.status.replaceAll("_", " ")}</span></td></tr>)}</tbody></table></div> : <div className="p-10 text-center text-[#806c60]">No orders yet. They will appear here after checkout.</div>}<div className="px-6 py-4 border-t border-[#eee4dc]"><button onClick={() => navigate("/admin/orders")} className="text-sm font-bold text-[#6b3c24] hover:underline">Manage all orders →</button></div></div>
            <div className="bg-[#2b1a12] text-white rounded-3xl p-6 shadow-xl relative overflow-hidden"><div className="absolute -right-16 -top-16 w-48 h-48 rounded-full border border-[#e2b06f]/15"/><p className="text-[10px] uppercase tracking-[.28em] text-[#e2b06f] font-bold">Quick actions</p><h3 className="text-2xl font-black mt-2">Manage CoffeeHub</h3><p className="text-sm text-[#d7c4b7] mt-2 leading-6">Your most-used tools, one click away.</p><div className="space-y-3 mt-7"><button onClick={() => navigate("/coffees")} className="w-full rounded-xl bg-[#fffaf4] text-[#3a2115] px-4 py-3 text-left font-bold hover:bg-[#f4e5d7]">☕ Manage coffee menu <span className="float-right">→</span></button><button onClick={() => navigate("/customers")} className="w-full rounded-xl bg-white/10 border border-white/10 px-4 py-3 text-left font-bold hover:bg-white/15">♙ Manage customers <span className="float-right">→</span></button><button onClick={() => navigate("/admin/orders")} className="w-full rounded-xl bg-white/10 border border-white/10 px-4 py-3 text-left font-bold hover:bg-white/15">▣ Manage orders <span className="float-right">→</span></button><button onClick={() => navigate("/")} className="w-full rounded-xl bg-white/10 border border-white/10 px-4 py-3 text-left font-bold hover:bg-white/15">↗ Open customer website <span className="float-right">→</span></button></div></div></section></>}
        <div className="lg:hidden grid grid-cols-2 gap-3 mt-6"><button onClick={() => navigate("/")} className="rounded-xl border border-[#dfd1c6] bg-white px-4 py-3 font-medium">↗ View Website</button><button onClick={handleLogout} className="rounded-xl bg-[#241610] text-white px-4 py-3 font-medium">Logout</button></div></div></main></div></div>;
}
export default Dashboard;
