import { useMemo, useState } from "react";
import "../reference-home.css";

interface Coffee { id:number; name:string; description:string; price:number; category:string; is_available:boolean; }
interface HomeProps { coffees:Coffee[]; onLogin:()=>void; }
const imageMap:Record<string,string>={cappuccino:"/coffee-images/cappuccino.jpg",americano:"/coffee-images/americano.jpg",latte:"/coffee-images/latte.jpg","cold brew":"/coffee-images/cold-brew.jpg",mocha:"/coffee-images/mocha.jpg",espresso:"/coffee-images/americano.jpg"};
const fallback="/coffee-images/coffee-default.svg";
const getImage=(name:string)=>imageMap[name.trim().toLowerCase()]||fallback;
const popularOrder=["Cappuccino","Americano","Latte","Cold Brew","Mocha"];

export default function Home({coffees,onLogin}:HomeProps){
 const[activeCategory,setActiveCategory]=useState("All");
 const available=useMemo(()=>coffees.filter(c=>c.is_available),[coffees]);
 const categories=useMemo(()=>["All",...Array.from(new Set(available.map(c=>c.category).filter(Boolean)))],[available]);
 const filtered=useMemo(()=>activeCategory==="All"?available:available.filter(c=>c.category===activeCategory),[activeCategory,available]);
 const popular=useMemo(()=>{const ordered=popularOrder.map(n=>available.find(c=>c.name.toLowerCase()===n.toLowerCase())).filter(Boolean) as Coffee[];return ordered.length?ordered:available.slice(0,5)},[available]);
 const addToCart=(coffee:Coffee)=>window.dispatchEvent(new CustomEvent("coffeehub:add-to-cart",{detail:coffee}));
 const scrollTo=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});
 return <main className="reference-home">
  <section className="ref-hero" id="home"><div className="ref-hero-backdrop"/><div className="ref-hero-content"><div className="ref-rating"><span className="google-g">G</span><strong>Google:</strong><span className="ref-stars">★★★★★</span><b>(4.9)</b></div><h1>Brewed to<br/><span>perfection</span></h1><p>Your perfect spot for coffee, pastries, and more.</p><div className="ref-hero-actions"><button className="ref-primary" onClick={()=>scrollTo("menu")}>Explore menu <span>→</span></button><button className="ref-story-play" onClick={()=>scrollTo("story")} aria-label="Watch our story">▶</button><button className="ref-story-link" onClick={()=>scrollTo("story")}>Watch our story</button></div></div><div className="ref-hero-art"><img src="/coffee-images/hero-coffee.jpg" alt="Coffee cup with latte art" onError={e=>{e.currentTarget.src=fallback}}/><span className="ref-floating-bean bean-1">●</span><span className="ref-floating-bean bean-2">●</span><span className="ref-floating-bean bean-3">●</span><span className="ref-leaf leaf-1">◆</span><span className="ref-leaf leaf-2">◆</span><div className="ref-quality">Premium<br/>Quality <i>⌁</i></div></div></section>
  <section className="ref-values" aria-label="CoffeeHub values"><div><span>◉</span><article><strong>Premium Beans</strong><small>Sourced from the best<br/>coffee regions.</small></article></div><div><span>♨</span><article><strong>Expertly Roasted</strong><small>Roasted to perfection<br/>for rich flavor.</small></article></div><div><span>☕</span><article><strong>Freshly Brewed</strong><small>Brewed fresh for you,<br/>every single time.</small></article></div><div><span>♥</span><article><strong>Made with Love</strong><small>Crafted with care<br/>and passion.</small></article></div></section>
  <section className="ref-popular" id="popular"><div className="ref-section-title"><h2>Our Popular Picks <em>⌁</em></h2><button onClick={()=>scrollTo("menu")}>View all menu <span>→</span></button></div><div className="ref-popular-grid">{popular.map(c=><article className="ref-product-card" key={c.id}><div className="ref-product-image"><img src={getImage(c.name)} alt={c.name} onError={e=>{e.currentTarget.src=fallback}}/><button className="ref-heart" aria-label={`Favourite ${c.name}`}>♡</button><span>{c.category||"Coffee"}</span></div><div className="ref-product-body"><h3>{c.name}</h3><p>{c.description}</p><strong>₹{c.price}</strong><button className="ref-add-round" onClick={()=>addToCart(c)} aria-label={`Add ${c.name} to cart`}>+</button></div></article>)}</div></section>
  <section className="ref-menu" id="menu"><div className="ref-menu-head"><div><small>THE COFFEE BAR</small><h2>Pick your perfect cup.</h2></div><p>Freshly prepared favorites, from bold espresso to smooth cold brews.</p></div><div className="ref-tabs">{categories.map(c=><button key={c} className={activeCategory===c?"active":""} onClick={()=>setActiveCategory(c)}>{c}</button>)}</div><div className="ref-menu-grid">{filtered.map(c=><article className="ref-menu-card" key={c.id}><img src={getImage(c.name)} alt={c.name} onError={e=>{e.currentTarget.src=fallback}}/><div><span>{c.category}</span><h3>{c.name}</h3><p>{c.description}</p><strong>₹{c.price}</strong><button onClick={()=>addToCart(c)}>Add to cart <b>+</b></button></div></article>)}</div>{!filtered.length&&<div className="ref-empty">No coffee available in this category.</div>}</section>
  <section className="ref-promo" id="contact"><div className="ref-promo-copy"><strong>10%</strong><span><b>Get 10% off on your first order!</b><small>Join our coffee community and enjoy exclusive offers.</small></span></div><button onClick={onLogin}>Join Now <span>→</span></button></section>
  <section className="ref-story" id="story"><div className="ref-story-card"><span>COFFEEHUB</span><strong>Good coffee<br/><i>takes its time.</i></strong><small>Roasted with intention · brewed with care</small></div><div><small>OUR STORY</small><h2>More than coffee.<br/><i>It's a moment.</i></h2><p>At CoffeeHub, we believe great coffee should slow things down. We source thoughtfully, roast in small batches, and make every cup with the kind of care you'd expect from your favourite neighbourhood café.</p><button className="ref-primary" onClick={onLogin}>Join CoffeeHub <span>→</span></button></div></section>
 </main>;
}
