import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

interface OrderItem { coffee_id: number; coffee_name: string; unit_price: number; quantity: number; line_total: number; }
interface Order { id: number; subtotal: number; delivery_fee: number; total: number; status: string; payment_method: string; created_at: string; items: OrderItem[]; }

const statusSteps = ["pending", "confirmed", "preparing", "ready", "out_for_delivery", "delivered"];

function MyOrders() {
  const navigate = useNavigate();
  const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => {
    const token = localStorage.getItem("customer_access_token");
    if (!token) { navigate("/customer-auth", { replace: true }); return; }
    fetch("http://127.0.0.1:8000/orders/", { headers: { Authorization: `Bearer ${token}` } })
      .then(async response => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || "Unable to load orders"); return body; })
      .then(data => setOrders(data)).catch(err => { if (err.message.includes("token") || err.message.includes("Customer")) { localStorage.removeItem("customer_access_token"); localStorage.removeItem("customer"); navigate("/customer-auth", { replace: true }); } else setError(err.message); }).finally(() => setLoading(false));
  }, [navigate]);
  const label = (status: string) => status.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
  return <main className="coffee-page min-h-screen py-12 px-5"><div className="coffee-container max-w-5xl mx-auto"><button onClick={() => navigate("/")} className="coffee-muted mb-6">← Back to CoffeeHub</button><div className="mb-9"><p className="text-[10px] uppercase tracking-[0.3em] text-[var(--coffee-brown)]">Your account</p><h1 className="text-4xl font-bold coffee-heading mt-2">My Orders</h1><p className="coffee-muted mt-2">Track every cup you've ordered from CoffeeHub.</p></div>{loading ? <div className="coffee-card bg-white p-10 text-center"><div className="text-5xl animate-pulse">☕</div><p className="coffee-muted mt-4">Loading your orders...</p></div> : error ? <div className="coffee-card bg-white p-8 text-center text-red-700">{error}</div> : !orders.length ? <div className="coffee-card bg-white p-10 text-center"><div className="text-6xl">📦</div><h2 className="text-2xl font-bold coffee-heading mt-5">No orders yet</h2><p className="coffee-muted mt-2">Your next coffee adventure starts here.</p><button onClick={() => navigate("/")} className="coffee-button mt-6">Browse menu →</button></div> : <div className="space-y-6">{orders.map(order => { const current = statusSteps.indexOf(order.status); return <article key={order.id} className="coffee-card bg-white p-6 sm:p-8"><div className="flex flex-wrap justify-between gap-4 border-b border-black/10 pb-5"><div><p className="text-xs coffee-muted">Order #{order.id}</p><h2 className="text-xl font-bold coffee-heading mt-1">{new Date(order.created_at).toLocaleString()}</h2></div><div className={`px-4 py-2 rounded-full text-xs font-bold uppercase tracking-wider ${order.status === "cancelled" ? "bg-red-50 text-red-700" : "bg-[#eee3d8] text-[var(--coffee-brown)]"}`}>{label(order.status)}</div></div><div className="grid sm:grid-cols-2 gap-4 mt-6">{order.items.map(item => <div key={item.coffee_id} className="flex justify-between gap-3 rounded-xl bg-[#fbf7f2] p-4"><div><p className="font-semibold coffee-heading">{item.coffee_name}</p><p className="text-xs coffee-muted mt-1">Qty {item.quantity} × ₹{item.unit_price}</p></div><strong>₹{item.line_total}</strong></div>)}</div>{order.status !== "cancelled" && <div className="mt-7"><div className="flex justify-between gap-1">{statusSteps.map((step, index) => <div key={step} className={`flex-1 text-center text-[9px] sm:text-[10px] uppercase ${index <= current ? "font-bold text-[var(--coffee-brown)]" : "text-gray-400"}`}><div className={`mx-auto mb-2 w-3 h-3 rounded-full ${index <= current ? "bg-[var(--coffee-brown)]" : "bg-gray-200"}`} />{label(step)}</div>)}</div></div>}<div className="flex flex-wrap justify-between gap-4 border-t border-black/10 mt-7 pt-5"><div className="text-sm coffee-muted">{order.payment_method === "cod" ? "Cash on Delivery" : order.payment_method}</div><div className="text-right"><p className="text-xs coffee-muted">Total</p><p className="text-2xl font-bold coffee-heading">₹{order.total}</p></div></div></article>; })}</div>}</div></main>;
}
export default MyOrders;
