import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

interface Item { coffee_name: string; quantity: number; line_total: number; }
interface Order { id: number; customer_id: number; customer_name: string; phone: string; address: string; city: string; pincode: string; total: number; status: string; created_at: string; items: Item[]; }
const statuses = ["pending", "confirmed", "preparing", "ready", "out_for_delivery", "delivered", "cancelled"];

function Orders() {
  const navigate = useNavigate(); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [updating, setUpdating] = useState<number | null>(null);
  const load = async () => { setLoading(true); setError(""); try { const token = localStorage.getItem("access_token"); const response = await fetch("http://127.0.0.1:8000/admin/orders/", { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || "Unable to load orders"); setOrders(body); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load orders"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const updateStatus = async (id: number, status: string) => { setUpdating(id); try { const token = localStorage.getItem("access_token"); const response = await fetch(`http://127.0.0.1:8000/admin/orders/${id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ status }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || "Unable to update status"); setOrders(current => current.map(order => order.id === id ? body : order)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update status"); } finally { setUpdating(null); } };
  return <main className="min-h-screen bg-[#f7f2ec] py-10 px-5"><div className="max-w-7xl mx-auto"><div className="flex flex-wrap items-center justify-between gap-4 mb-8"><div><button onClick={() => navigate("/dashboard")} className="text-sm text-gray-500 hover:text-amber-900">← Dashboard</button><h1 className="text-4xl font-bold text-amber-950 mt-3">Orders</h1><p className="text-gray-500 mt-1">Manage incoming CoffeeHub orders.</p></div><button onClick={load} className="border border-black/10 bg-white px-5 py-2.5 rounded-xl font-semibold">Refresh</button></div>{error && <div className="bg-red-50 border border-red-100 text-red-700 rounded-xl px-4 py-3 mb-5">{error}</div>}{loading ? <div className="bg-white rounded-2xl p-10 text-center">Loading orders...</div> : !orders.length ? <div className="bg-white rounded-2xl p-12 text-center"><div className="text-6xl">📦</div><h2 className="text-2xl font-bold mt-4">No orders yet</h2></div> : <div className="space-y-5">{orders.map(order => <article key={order.id} className="bg-white rounded-2xl shadow-sm border border-black/5 p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs text-gray-500">Order #{order.id} · {new Date(order.created_at).toLocaleString()}</p><h2 className="text-xl font-bold text-amber-950 mt-1">{order.customer_name}</h2><p className="text-sm text-gray-500 mt-1">{order.phone} · {order.address}, {order.city} - {order.pincode}</p></div><div className="text-right"><p className="text-2xl font-bold text-amber-900">₹{order.total}</p><select value={order.status} disabled={updating === order.id} onChange={e => updateStatus(order.id, e.target.value)} className="mt-2 border border-black/10 rounded-lg px-3 py-2 text-sm bg-white">{statuses.map(status => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-6">{order.items.map((item, index) => <div key={`${item.coffee_name}-${index}`} className="rounded-xl bg-[#fbf7f2] p-4"><p className="font-semibold text-amber-950">{item.coffee_name}</p><p className="text-xs text-gray-500 mt-1">Qty {item.quantity} · ₹{item.line_total}</p></div>)}</div></article>)}</div>}</div></main>;
}
export default Orders;
